<?php
namespace Sagres\Component\FileSystem\Locator\Node;


require_once '/home/nuno/workspace/Sagres-FileSystem/Sagres/Component/FileSystem/Locator/Node/AbstractNode.php';

/**
 * Test class for AbstractNode.
 * Generated by PHPUnit on 2012-03-14 at 15:23:21.
 */
class AbstractNodeTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var AbstractNode
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new AbstractNode;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers Sagres\Component\FileSystem\Locator\Node\AbstractNode::isReadable
     * @todo Implement testIsReadable().
     */
    public function testIsReadable()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Sagres\Component\FileSystem\Locator\Node\AbstractNode::isWritable
     * @todo Implement testIsWritable().
     */
    public function testIsWritable()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Sagres\Component\FileSystem\Locator\Node\AbstractNode::exists
     * @todo Implement testExists().
     */
    public function testExists()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Sagres\Component\FileSystem\Locator\Node\AbstractNode::getName
     * @todo Implement testGetName().
     */
    public function testGetName()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Sagres\Component\FileSystem\Locator\Node\AbstractNode::getPath
     * @todo Implement testGetPath().
     */
    public function testGetPath()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Sagres\Component\FileSystem\Locator\Node\AbstractNode::getType
     * @todo Implement testGetType().
     */
    public function testGetType()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Sagres\Component\FileSystem\Locator\Node\AbstractNode::__toString
     * @todo Implement test__toString().
     */
    public function test__toString()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }
}
?>
