<?php
namespace Sagres\Component\FileSystem\Locator\Node;



/**
 * Test class for FolderNode.
 * Generated by PHPUnit on 2012-03-14 at 15:39:15.
 */
class FolderNodeTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var FolderNode
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    private function getFixturesPath($path)
    {
        return __DIR__ . '/../../../../../fixtures/' . $path;
    }

    /**
     * @covers Sagres\Component\FileSystem\Locator\Node\FolderNode::getPath
     * @covers Sagres\Component\FileSystem\Locator\Node\FolderNode::__construct
     * @covers Sagres\Component\FileSystem\Locator\Node\FolderNode::getType
     * @covers Sagres\Component\FileSystem\Locator\Node\FolderNode::SetType
     */
    public function testGetPath()
    {
        $path = $this->getFixturesPath('');
        $o = new FolderNode(substr($path, 0, strlen($path)-1));

        $this->assertEquals($o::TYPE_FOLDER, $o->getType());
        $this->assertEquals($path, $o->getPath());
    }

    /**
     * @covers Sagres\Component\FileSystem\Locator\Node\AbstractNode::isFolder
     */
    public function test_isFolder()
    {
        $path = $this->getFixturesPath('');
        $o = new FolderNode(substr($path, 0, strlen($path)-1));

        $this->assertFalse($o->isFile());
        $this->assertTrue($o->isFolder());
        $this->assertFalse($o->isLink());
    }
}
?>
