<?php
namespace Sagres\Component\FileSystem\Locator\Node;



/**
 * Test class for LinkNode.
 * Generated by PHPUnit on 2012-03-14 at 15:44:42.
 */
class LinkNodeTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var LinkNode
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    private function getFixturesPath($path)
    {
        return __DIR__ . '/../../../../../fixtures/' . $path;
    }

    /**
     * @covers Sagres\Component\FileSystem\Locator\Node\LinkNode::getType
     * @covers Sagres\Component\FileSystem\Locator\Node\LinkNode::setType
     * @covers Sagres\Component\FileSystem\Locator\Node\LinkNode::__construct
     */
    public function testGetType()
    {
        $path = $this->getFixturesPath('linked.file');
        $o = new LinkNode($path);
        $this->assertEquals($o::TYPE_LINK, $o->getType());
    }

    /**
     * @covers Sagres\Component\FileSystem\Locator\Node\AbstractNode::isLink
     */
    public function test__isLink()
    {
        $path = $this->getFixturesPath('linked.file');
        $o = new LinkNode($path);

        $this->assertFalse($o->isFile());
        $this->assertFalse($o->isFolder());
        $this->assertTrue($o->isLink());
    }
}
?>
