<?php
namespace Sagres\Component\FileSystem;



/**
 * Test class for Node.
 * Generated by PHPUnit on 2012-03-19 at 14:26:55.
 */
class NodeTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var Node
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = $this->getReadWriteFile();
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    private function getFixturesPath($path)
    {
        return __DIR__ . '/../../../fixtures/' . $path;
    }

    protected function getReadWriteFile()
    {
        $file = $this->getFixturesPath('read.write.file');
        $o = new Node($file);
        return $o;
    }


    /**
     * @covers Sagres\Component\FileSystem\Node::exists
     * @covers Sagres\Component\FileSystem\Node::__construct
     * @todo Implement testExists().
     */
    public function testExists()
    {
        $this->assertTrue($this->object->exists());
    }

    /**
     * @covers Sagres\Component\FileSystem\Node::getOctalPermissions
     * @todo Implement testGetOctalPermissions().
     */
    public function testGetOctalPermissions()
    {
         $this->assertEquals("0777",  $this->object->getOctalPermissions());
    }

    /**
     * @covers Sagres\Component\FileSystem\Node::getHumanReadablePermissions
     * @todo Implement testGetHumanReadablePermissions().
     */
    public function testGetHumanReadablePermissions()
    {
       $this->assertEquals("-rwxrwxrwx",  $this->object->getHumanReadablePermissions());
    }
}
?>
